/**
 * Writes frontend/backend.json from the BACKEND_URL environment variable.
 *
 * This used to read frontend/app.js and rewrite a hard-coded `backendUrl` inside
 * it. That file stopped existing when the frontend was split into modules, so the
 * script threw ENOENT on every run — which failed the Vercel build, which is why
 * the deployed site kept serving whatever was last built successfully. A build that
 * fails loudly still deploys nothing; the old version simply stays up.
 *
 * The frontend resolves its API URL at startup now (see resolveBackendUrl in
 * shared.js), reading this file first. So the build's only job is to turn a Vercel
 * environment variable into that file, which keeps the URL out of the repository
 * and lets one commit deploy against different backends.
 *
 * Missing BACKEND_URL is not an error. The file is written with an empty value and
 * the page falls back to its own origin — correct when the API is proxied under the
 * same domain, and the right default for a preview build nobody has configured yet.
 */
const fs = require("fs");
const path = require("path");

const target = path.join(__dirname, "..", "frontend", "backend.json");
const backendUrl = (process.env.BACKEND_URL || "").trim().replace(/\/$/, "");

if (backendUrl) {
  console.log(`Frontend will call the API at ${backendUrl}`);
} else {
  console.log(
    "BACKEND_URL is not set — the page will fall back to its own origin, " +
      "which only works if the API is proxied under the same domain."
  );
}

fs.writeFileSync(
  target,
  JSON.stringify(
    {
      _comment:
        "Generated by scripts/build.js from the BACKEND_URL environment variable. " +
        "Edit BACKEND_URL in your host's settings rather than this file.",
      backendUrl,
    },
    null,
    2
  ) + "\n"
);

console.log(`Wrote ${path.relative(path.join(__dirname, ".."), target)}`);
